/* Season context the page reads beside each week file. Rebuilt on every pull.

     node tools/context.js            (from news/)   or   require('./context').build()

   Writes three plain script data files (the page stays file:// friendly, no fetch):
     data/ranks2026.js     RANKS26: every team's Power Ratings rank and Elo, read from the
                           betting site's published state (../betting/state.json), the same
                           board the betting page shows. Replaces the old preseason rank.
     data/players2026.js   PLAYERS26: team -> { name: position } from the nflverse roster,
                           keyed by full name, football name and first name, so the page
                           can write "(QB)" after a player's name.
     data/units2026.js     UNITS26: the Deep Dive. Six units per team with a league rank,
                           the numbers behind it, and who is playing there:
                             qb     passing offense       EPA per dropback
                             ol     offensive line        sack rate allowed, yards per carry
                             rb     run game              rushing EPA per carry, yards per carry
                             rec    receivers             YAC per catch, share of throws gaining 20+
                             front  pass and run rush     sacks + QB hits per dropback, rush EPA allowed
                             db     defensive backs       pass EPA allowed per dropback, INT + PD rate
                           Team numbers blend 2025 (weighted as PRIOR_GAMES games) with every
                           2026 game so far, so each week this season counts for more.
   Sources: nflverse-data releases (team stats 2025 and 2026, player stats 2026, snap counts
   2026, roster 2026). A source that cannot be reached leaves its file as it was.        */
'use strict';
const fs = require('fs'), path = require('path');

const SEASON = 2026, PRIOR = 2025, PRIOR_GAMES = 4;
const REL = 'https://github.com/nflverse/nflverse-data/releases/download';
const URLS = {
  team25: `${REL}/stats_team/stats_team_week_${PRIOR}.csv`,
  team26: `${REL}/stats_team/stats_team_week_${SEASON}.csv`,
  player26: `${REL}/stats_player/stats_player_week_${SEASON}.csv`,
  snaps26: `${REL}/snap_counts/snap_counts_${SEASON}.csv`,
  roster26: `${REL}/rosters/roster_${SEASON}.csv`,
};
/* the tracker uses LAR for the Rams; nflverse uses LA (and a few old codes) */
const AB = { LA: 'LAR', STL: 'LAR', OAK: 'LV', SD: 'LAC', WSH: 'WAS', JAC: 'JAX' };
const ab = t => AB[t] || t;

function parseCSV(text) {
  const rows = []; let row = [], cell = '', q = false;
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (q) { if (ch === '"') { if (text[i + 1] === '"') { cell += '"'; i++; } else q = false; } else cell += ch; }
    else if (ch === '"') q = true;
    else if (ch === ',') { row.push(cell); cell = ''; }
    else if (ch === '\n') { row.push(cell.replace(/\r$/, '')); rows.push(row); row = []; cell = ''; }
    else cell += ch;
  }
  if (cell || row.length) { row.push(cell); rows.push(row); }
  const head = rows.shift();
  return rows.filter(r => r.length === head.length).map(r => Object.fromEntries(head.map((h, i) => [h, r[i]])));
}
async function getCSV(url) {
  let last;
  for (const headers of [{ 'User-Agent': 'nfl-hub-season-tracker/1.0 (+https://github.com/DEMON-X13/nfl-hub)' }, {}]) {
    try { const r = await fetch(url, { headers, redirect: 'follow' }); if (r.ok) return parseCSV(await r.text()); last = new Error(r.status + ' ' + url); }
    catch (e) { last = e; }
  }
  throw last;
}
const num = v => { const x = parseFloat(v); return isFinite(x) ? x : 0; };
const writeData = (file, name, obj, extra = '') =>
  fs.writeFileSync(file, `/* Generated by tools/context.js. Do not edit by hand. */\nconst ${name} = ${JSON.stringify(obj)};\n${extra}`);

/* ---------------- power ranks from the betting site's published board ---------------- */
function ranks(root, out) {
  const stateFile = path.resolve(root, '..', 'betting', 'state.json');
  if (!fs.existsSync(stateFile)) { console.log('ranks2026.js kept: ../betting/state.json not found'); return; }
  const st = JSON.parse(fs.readFileSync(stateFile, 'utf8'));
  const teams = Object.entries(st.teams || {}).map(([t, v]) => [ab(t), v.elo]).filter(([, e]) => isFinite(e)).sort((a, b) => b[1] - a[1]);
  if (teams.length < 32) { console.log(`ranks2026.js kept: only ${teams.length} teams on the board`); return; }
  const R = {}; teams.forEach(([t, e], i) => { R[t] = { rank: i + 1, elo: Math.round(e) }; });
  const asof = st.published ? new Date(st.published).toISOString().slice(0, 10) : '';
  writeData(path.join(out, 'ranks2026.js'), 'RANKS26', R, `const RANKS26_ASOF = ${JSON.stringify(asof)};\n`);
  console.log(`ranks2026.js: ${teams.length} teams, #1 ${teams[0][0]}, as of ${asof}`);
}

/* ---------------- positions from the roster ---------------- */
/* writers use either form of a first name; the roster keeps one */
const NICK = {};
for (const [a, b] of [['Josh', 'Joshua'], ['Mike', 'Michael'], ['Matt', 'Matthew'], ['Chris', 'Christopher'], ['Nick', 'Nicholas'],
  ['Jon', 'Jonathan'], ['Rob', 'Robert'], ['Bob', 'Robert'], ['Will', 'William'], ['Dan', 'Daniel'], ['Tony', 'Anthony'], ['Alex', 'Alexander'],
  ['Ben', 'Benjamin'], ['Zach', 'Zachary'], ['Tom', 'Thomas'], ['Jake', 'Jacob'], ['Joe', 'Joseph'], ['Sam', 'Samuel'], ['Andy', 'Andrew'],
  ['Drew', 'Andrew'], ['Jim', 'James'], ['Jimmy', 'James'], ['Dave', 'David'], ['Ed', 'Edward'], ['Greg', 'Gregory'], ['Jeff', 'Jeffrey'],
  ['Pat', 'Patrick'], ['Steve', 'Steven'], ['Tim', 'Timothy'], ['Cam', 'Cameron'], ['Trey', 'Treyvon'], ['Kenny', 'Kenneth'], ['Ken', 'Kenneth']]) {
  (NICK[a] ??= []).push(b); (NICK[b] ??= []).push(a);
}
function players(roster, out) {
  const P = {};
  for (const r of roster) {
    if (['CUT', 'RET'].includes(r.status)) continue;
    const team = ab(r.team), pos = r.depth_chart_position || r.position; if (!team || !pos) continue;
    const t = (P[team] ??= {});
    const firsts = new Set([r.football_name, r.first_name].filter(Boolean));
    for (const f of [...firsts]) for (const alt of (NICK[f] || [])) firsts.add(alt);
    for (const n of new Set([r.full_name, ...[...firsts].map(f => `${f} ${r.last_name}`)])) {
      if (n && n.trim().split(' ').length >= 2 && !n.includes('undefined') && !t[n]) t[n] = pos;
    }
  }
  const n = Object.values(P).reduce((a, t) => a + Object.keys(t).length, 0);
  if (Object.keys(P).length < 32) { console.log(`players2026.js kept: roster covered ${Object.keys(P).length} teams`); return P; }
  writeData(path.join(out, 'players2026.js'), 'PLAYERS26', P);
  console.log(`players2026.js: ${n} names across ${Object.keys(P).length} teams`);
  return P;
}

/* ---------------- Deep Dive unit grades ---------------- */
function teamTotals(rows) {
  /* per team: offence totals from its own rows, defence-allowed totals from opponents' rows */
  const T = {};
  const get = t => (T[t] ??= { g: 0, att: 0, sk: 0, pepa: 0, comp: 0, yac: 0, p20: 0, car: 0, ryd: 0, repa: 0,
    oatt: 0, osk: 0, opepa: 0, ocar: 0, oryd: 0, orepa: 0, dsk: 0, dhit: 0, dint: 0, dpd: 0 });
  for (const r of rows) {
    if (r.season_type && r.season_type !== 'REG') continue;
    const t = get(ab(r.team)), o = get(ab(r.opponent_team));
    t.g++; t.att += num(r.attempts); t.sk += num(r.sacks_suffered); t.pepa += num(r.passing_epa); t.comp += num(r.completions);
    t.yac += num(r.passing_yards_after_catch); t.p20 += num(r.passing_20); t.car += num(r.carries); t.ryd += num(r.rushing_yards); t.repa += num(r.rushing_epa);
    t.dsk += num(r.def_sacks); t.dhit += num(r.def_qb_hits); t.dint += num(r.def_interceptions); t.dpd += num(r.def_pass_defended);
    o.oatt += num(r.attempts); o.osk += num(r.sacks_suffered); o.opepa += num(r.passing_epa); o.ocar += num(r.carries); o.oryd += num(r.rushing_yards); o.orepa += num(r.rushing_epa);
  }
  return T;
}
function blend(prior, cur) {
  /* 2025 scaled to PRIOR_GAMES games, plus every 2026 game at full weight */
  const out = {};
  for (const t of new Set([...Object.keys(prior), ...Object.keys(cur)])) {
    const p = prior[t], c = cur[t], o = {};
    const sp = p && p.g ? PRIOR_GAMES / p.g : 0;
    for (const k of Object.keys(p || c)) o[k] = (p ? p[k] * sp : 0) + (c ? c[k] : 0);
    o.g26 = c ? c.g : 0;
    out[t] = o;
  }
  return out;
}
const div = (a, b) => b > 0 ? a / b : null;
function rankOf(values, t, higherBetter) {
  const arr = Object.entries(values).filter(([, v]) => v != null).sort((a, b) => higherBetter ? b[1] - a[1] : a[1] - b[1]);
  return arr.findIndex(([k]) => k === t) + 1;
}
function units(team25, team26, player26, snaps26, out, rosterPos = {}) {
  const B = blend(teamTotals(team25), teamTotals(team26));
  const teams = Object.keys(B).filter(t => t.length >= 2 && t.length <= 3);
  const M = {};
  for (const t of teams) {
    const x = B[t], db = x.att + x.sk, odb = x.oatt + x.osk;
    M[t] = {
      pass_epa: div(x.pepa, db), sack_rate: div(x.sk, db), ypc: div(x.ryd, x.car), rush_epa: div(x.repa, x.car),
      yac: div(x.yac, x.comp), expl: div(x.p20, x.att),
      press: div(x.dsk + x.dhit, odb), o_rush_epa: div(x.orepa, x.ocar), o_ypc: div(x.oryd, x.ocar),
      o_pass_epa: div(x.opepa, odb), ballhawk: div(x.dint + x.dpd, odb), g26: x.g26,
    };
  }
  const col = k => Object.fromEntries(teams.map(t => [t, M[t][k]]));
  const z = (k, sign) => {
    const v = teams.map(t => M[t][k]).filter(x => x != null); const mu = v.reduce((a, b) => a + b, 0) / v.length;
    const sd = Math.sqrt(v.reduce((a, b) => a + (b - mu) ** 2, 0) / v.length) || 1;
    return t => M[t][k] == null ? 0 : sign * (M[t][k] - mu) / sd;
  };
  const score = {
    qb: t => z('pass_epa', 1)(t),
    ol: t => (z('sack_rate', -1)(t) + z('ypc', 1)(t)) / 2,
    rb: t => (z('rush_epa', 1)(t) + z('ypc', 1)(t)) / 2,
    rec: t => (z('yac', 1)(t) + z('expl', 1)(t)) / 2,
    front: t => (z('press', 1)(t) + z('o_rush_epa', -1)(t)) / 2,
    db: t => (z('o_pass_epa', -1)(t) + z('ballhawk', 1)(t)) / 2,
  };
  score.passD = t => (z('o_pass_epa', -1)(t) + z('ballhawk', 1)(t) + z('press', 1)(t)) / 3;
  score.runD = t => (z('o_rush_epa', -1)(t) + z('o_ypc', -1)(t)) / 2;
  const S = {}, R = {};
  for (const u of Object.keys(score)) { S[u] = Object.fromEntries(teams.map(t => [t, score[u](t)])); }
  for (const u of Object.keys(score)) { R[u] = Object.fromEntries(teams.map(t => [t, rankOf(S[u], t, true)])); }
  /* sub-ranks for the numbers shown */
  const sub = {
    pass_epa: t => rankOf(col('pass_epa'), t, true), sack_rate: t => rankOf(col('sack_rate'), t, false), ypc: t => rankOf(col('ypc'), t, true),
    rush_epa: t => rankOf(col('rush_epa'), t, true), yac: t => rankOf(col('yac'), t, true), expl: t => rankOf(col('expl'), t, true),
    press: t => rankOf(col('press'), t, true), o_rush_epa: t => rankOf(col('o_rush_epa'), t, false), o_pass_epa: t => rankOf(col('o_pass_epa'), t, false),
    ballhawk: t => rankOf(col('ballhawk'), t, true),
  };

  /* who is playing each unit, from 2026 player stats and snap counts */
  const P = {};
  const add = (t, n, pos, k, v) => { const e = ((P[t] ??= {})[n] ??= { pos, att: 0, car: 0, tgt: 0, sk: 0, hit: 0, tfl: 0, int: 0, pd: 0, osn: 0, dsn: 0 }); e[k] += v; if (!e.pos && pos) e.pos = pos; };
  for (const r of player26) {
    if (r.season_type && r.season_type !== 'REG') continue;
    const t = ab(r.team), n = r.player_display_name || r.player_name, pos = r.position;
    add(t, n, pos, 'att', num(r.attempts)); add(t, n, pos, 'car', num(r.carries)); add(t, n, pos, 'tgt', num(r.targets));
    add(t, n, pos, 'sk', num(r.def_sacks)); add(t, n, pos, 'hit', num(r.def_qb_hits)); add(t, n, pos, 'tfl', num(r.def_tackles_for_loss));
    add(t, n, pos, 'int', num(r.def_interceptions)); add(t, n, pos, 'pd', num(r.def_pass_defended));
  }
  for (const r of snaps26) {
    if (r.game_type && r.game_type !== 'REG') continue;
    const t = ab(r.team), n = r.player, pos = r.position;
    add(t, n, pos, 'osn', num(r.offense_snaps)); add(t, n, pos, 'dsn', num(r.defense_snaps));
    const e = P[t][n]; if (pos) e.pos = e.pos && e.pos !== pos && ['DB', 'DL', 'OL', 'LB'].includes(e.pos) ? pos : (e.pos || pos);
  }
  /* the position shown is the roster's where we have it; the stat feeds use codes like SAF, OT and HB */
  const FEED = { SAF: 'S', OT: 'T', OG: 'G', HB: 'RB', EDGE: 'OLB' };
  const shown = (t, n, pos) => (rosterPos[t] && rosterPos[t][n]) || FEED[pos] || pos;
  const top = (t, filter, key, k) => Object.entries(P[t] || {}).filter(([, e]) => filter(e.pos || '') && e[key] > 0).sort((a, b) => b[1][key] - a[1][key]).slice(0, k).map(([n, e]) => ({ n, pos: shown(t, n, e.pos) }));
  const isQB = p => p === 'QB', isRB = p => ['RB', 'HB', 'FB'].includes(p), isRec = p => ['WR', 'TE'].includes(p);
  const isOL = p => ['T', 'G', 'C', 'OL', 'OT', 'OG'].includes(p), isFront = p => ['DE', 'DT', 'NT', 'DL', 'LB', 'OLB', 'ILB', 'MLB', 'EDGE'].includes(p);
  const isDB = p => ['CB', 'S', 'FS', 'SS', 'DB', 'SAF'].includes(p);
  const frontKey = (t) => Object.entries(P[t] || {}).filter(([, e]) => isFront(e.pos || '')).map(([n, e]) => [n, e, 2 * e.sk + e.hit + e.tfl + e.dsn / 100]).sort((a, b) => b[2] - a[2]).slice(0, 3).map(([n, e]) => ({ n, pos: shown(t, n, e.pos) }));

  const U = {};
  const r2 = v => v == null ? null : Math.round(v * 100) / 100, pc = v => v == null ? null : Math.round(v * 1000) / 10, r1 = v => v == null ? null : Math.round(v * 10) / 10;
  for (const t of teams) {
    const m = M[t];
    U[t] = {
      g26: m.g26,
      qb: { rank: R.qb[t], who: top(t, isQB, 'att', 1), stats: [['EPA per dropback', r2(m.pass_epa), sub.pass_epa(t)]] },
      ol: { rank: R.ol[t], who: top(t, isOL, 'osn', 5), stats: [['sack rate allowed', pc(m.sack_rate), sub.sack_rate(t), '%'], ['yards per carry', r1(m.ypc), sub.ypc(t)]] },
      rb: { rank: R.rb[t], who: top(t, isRB, 'car', 2), stats: [['rush EPA per carry', r2(m.rush_epa), sub.rush_epa(t)], ['yards per carry', r1(m.ypc), sub.ypc(t)]] },
      rec: { rank: R.rec[t], who: top(t, isRec, 'tgt', 3), stats: [['YAC per catch', r1(m.yac), sub.yac(t)], ['throws gaining 20+', pc(m.expl), sub.expl(t), '%']] },
      front: { rank: R.front[t], who: frontKey(t), stats: [['pressure (sacks and QB hits) per dropback', pc(m.press), sub.press(t), '%'], ['rush EPA allowed per carry', r2(m.o_rush_epa), sub.o_rush_epa(t)]] },
      db: { rank: R.db[t], who: top(t, isDB, 'dsn', 3), stats: [['pass EPA allowed per dropback', r2(m.o_pass_epa), sub.o_pass_epa(t)], ['INT + passes defended per dropback', pc(m.ballhawk), sub.ballhawk(t), '%']] },
      /* what the opposing offence faces: whole pass defence (coverage and rush) and run defence */
      vs: { passD: R.passD[t], runD: R.runD[t] },
    };
  }
  if (teams.length < 32) { console.log(`units2026.js kept: stats covered ${teams.length} teams`); return; }
  const g26 = Math.max(...teams.map(t => M[t].g26));
  writeData(path.join(out, 'units2026.js'), 'UNITS26', U,
    `const UNITS26_BASIS = ${JSON.stringify(`2025 season counted as ${PRIOR_GAMES} games, plus ${g26} game${g26 === 1 ? '' : 's'} of 2026`)};\n`);
  console.log(`units2026.js: ${teams.length} teams, ${g26} 2026 game(s) blended with 2025`);
}

async function build(opts = {}) {
  const root = opts.root || path.resolve(__dirname, '..');
  const out = opts.out || path.join(root, 'data');
  fs.mkdirSync(out, { recursive: true });
  try { ranks(root, out); } catch (e) { console.log('ranks2026.js kept:', e.message); }
  let roster = null, t25 = null, t26 = null, p26 = null, s26 = null;
  try { roster = await getCSV(URLS.roster26); } catch (e) { console.log('roster unavailable:', e.message); }
  let rosterPos = {};
  if (roster) { try { rosterPos = players(roster, out) || {}; } catch (e) { console.log('players2026.js kept:', e.message); } }
  try { [t25, t26, p26, s26] = await Promise.all([getCSV(URLS.team25), getCSV(URLS.team26), getCSV(URLS.player26), getCSV(URLS.snaps26).catch(() => [])]); }
  catch (e) { console.log('units2026.js kept: stats unavailable:', e.message); return; }
  try { units(t25, t26, p26, s26, out, rosterPos); } catch (e) { console.log('units2026.js kept:', e.message); }
}

module.exports = { build };
if (require.main === module) build().catch(e => { console.error(e); process.exit(1); });
